### ISSUE TITLE
Publish the current master on npm

### ISSUE THREAD

**Issue by toddbluhm** [shakefon/consistency#6]
I just ran into the 500 unhandled exception error that was fixed last January. When comparing the npm code with the current master it appears the current master has fixed this issue, but those fixes never got published to npm. It would be great if you could take a couple seconds to get the current master version published on npm. Thanks 😄

**Comment by dstevensio** [comment]
@toddbluhm thank you for contributing to this project - for some reason I didn't get a notification and only just saw this issue and the PR you submitted. I've merged the PR and published to NPM @ 1.1.0 

Sorry it took so long from your contribution to inclusion.
